title:            "吕小荣"
description:      "一个程序员"
url:              "http://mednoter.com"
signoff:          "吕小荣"
disqus_shortname: "mednoter"
facebook_appid:   "407484809306168"
google_analytics: "UA-103214300-1"
timezone:         Asia/Beijing
highlighter:      pygments
future:           true
repository_url:   https://github.com/xiaoronglv/xiaoronglv.github.io

links:
  - name:         Blog
    url:          /
  - name:         Friends
    url:          /links.html
  - name:         RSS
    url:          /feed.xml
  - name:         About
    url:          /about.html

permalink:        /:title.html
markdown:         kramdown
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
sass:
  style: compressed
